### PR TITLE
Creates virtual env for the project

### LINKED ISSUE #20: Check/install requirements & use venv

### PR DESCRIPTION
**Pull request by JoaoCarabetta**
It creates virtual env, enters it and install requirements.txt

closes #20

### CODE REVIEW

**Comment by JoaoCarabetta** [comment]
@fernandascovino can you review it?

**Comment by fernandascovino** [comment]
review it, better English please

**Comment by fernandascovino** [comment]
@JoaoCarabetta what do I get in return?

**Comment by JoaoCarabetta** [comment]
by reviewing it?

a purple porche

**Comment by fernandascovino** [comment]
I prefer seeing you soon 😚

**Review by fernandascovino — APPROVED** [review]
great job bb

**Pull request merged**
